apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace-resource-dispatcher
  labels:
    user.kubeflow.org/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace-resource-dispatcher-2
  labels:
    user.kubeflow.org/enabled: "true"
